# Generated by Django 5.2.8 on 2025-11-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('professores', models.ManyToManyField(related_name='disciplinas', to='core.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='cursos', to='core.disciplina')),
            ],
        ),
    ]
