# Generated by Django 5.2.8 on 2025-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disciplina_professor_alter_avaliacao_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='professor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='cursos', to='core.disciplina')),
            ],
        ),
    ]
