# Generated by Django 5.2.8 on 2025-11-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disciplina_professor_alter_avaliacao_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professores',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='professor',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
