# Generated by Django 5.2.8 on 2025-11-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_disciplina_professores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaAntiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_semestral', models.CharField(max_length=10)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prova', models.CharField(max_length=10)),
                ('arquivo', models.FileField(upload_to='provas/')),
                ('prova_antiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provaantiga')),
            ],
        ),
    ]
