# Generated by Django 5.2.9 on 2025-12-03 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_professor_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('membros_count', models.IntegerField(default=0)),
                ('icone_url', models.URLField(blank=True, max_length=300, null=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades_inscritas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
