# Generated by Django 6.0 on 2025-12-05 00:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postagem_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaantiga',
            name='periodo_semestral',
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='arquivo',
            field=models.FileField(default='', upload_to=core.models.renomear_prova),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='grau',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('PF', 'PF'), ('2CH', '2ª Chamada'), ('Outro', 'Outro')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='periodo',
            field=models.CharField(default='', help_text='Ex: 2023.1', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArquivoProva',
        ),
    ]
