# Generated by Django 5.2.8 on 2025-12-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postagem_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data_criacao']},
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='curtidas_count',
        ),
        migrations.AddField(
            model_name='postagem',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postagem',
            name='salvamentos',
            field=models.ManyToManyField(blank=True, related_name='salvamentos_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.postagem'),
        ),
    ]
