# Generated by Django 6.0 on 2025-12-05 01:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_provaantiga_periodo_semestral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provaantiga',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.renomear_prova),
        ),
    ]
