# Generated by Django 6.0 on 2025-12-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='arquivo_anexo',
            field=models.FileField(blank=True, null=True, upload_to='post_anexos/'),
        ),
    ]
