# Generated by Django 6.0 on 2025-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='icone_url',
        ),
        migrations.AddField(
            model_name='comunidade',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comunidade',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='comunidade_icones/'),
        ),
    ]
