# Generated by Django 6.0 on 2025-12-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mensagemcomunidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='conteudo',
        ),
    ]
