# Generated by Django 6.0 on 2025-12-07 23:22

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_texto_comentario_conteudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaantiga',
            name='periodo_semestral',
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.renomear_prova),
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='grau',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('PF', 'PF'), ('2CH', '2ª Chamada'), ('Outro', 'Outro')], default='Outro', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='periodo',
            field=models.CharField(default='Desconhecido', help_text='Ex: 2023.1', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=100)),
                ('periodo', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
