# Generated by Django 6.0 on 2025-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_provaantiga_periodo_semestral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
